### ISSUE TITLE
Observaciones de mejora

### ISSUE THREAD

**Issue by AnderMendoza** [Jankarurosu/juego-numero-secreto#1]
## Hola Giancarlos 👋
Probé el juego y esta interesante la verdad, encontré algunos puntos que me parece que podrían mejorar este juego:
1. No debería dejar jugar si el input este vacío (podrías insertar alguna advertencia).
2. Podrías agregar el evento de la tecla enter para jugar en vez de solo dar clics.

Veré que más se me ocurre, iré actualizando el post de ser necesario. Saludos.

**Comment by Jankarurosu** [comment]
Hola, Anderson

Gracias por tu comentario de mejora, lo he tomado en cuenta.

Los puntos mejorados fueron los siguientes:

1. Si no se detecta un valor en el input, el usuario no podrá jugar y se mostrará el mensaje "¡Debes ingresar un número!".
2. Al ingresar un valor en el input y presionar la tecla "Enter", el juego se ejecutará automáticamente sin necesidad de hacer clic en el botón "Jugar".

Puedes ver los cambios implementados en este [commit](https://github.com/Jankarurosu/juego-numero-secreto/commit/e1f562c37d2fc8f161d52ab3212a1ad98a68cb72).

¡Gracias nuevamente por tu comentario!
